MDScreen:
    name: "splash-screen"
    MDFloatLayout:
        Image:
            source: "assets/ckure.png"
            size_hint: .6, .6
            pos_hint: {"center_x": .5, "center_y": .55}
            
    MDLabel:
        text: "Automated Vehicle Damage Assessment"
        pos_hint:{"center_x": .5, "center_y": .1}
        halign: "center"
        font_size: "18sp"
        font_name: "fonts/Oswald-Regular.ttf"

        